### ISSUE TITLE
Priority setting

### ISSUE THREAD

**Issue by fietstasss** [makah/pushover-vba#1]
Hi, 

How is one abled to set a 'priority' to the pushover messages? 

Thanks in advance!

**Comment by makah** [comment]
According to Pushover's API you can try something like my example 3

`Sub Example3()
    Dim myApp As String, theGroup As String
    
    myApp = "my_application_token"
    theGroup = "my_Group_or_user_token"
    message = "Hello my PushoOver-VBA Helper 3"
    
    Debug.Print Pushover.PostOp(myApp, theGroup, message, "priority", "1")
    End Sub`
